version: '3.3'
services:
  backend:
    build: .
    image: docker-teaches-code
    ports: ["8080:8080"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/dtc:/tmp/dtc
  golang:
    build: lang/golang
    image: dtc-golang
  python:
    build: lang/python
    image: dtc-python