version: '3.3'
services:
  backend:
    build: .
    image: docker-teaches-code
    ports: ["8080:8080"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/dtc:/tmp/dtc
  cpp:
    build: envs/cpp
    image: dtc-cpp
  dockerfile:
    build: envs/dockerfile
    image: dtc-dockerfile
  golang:
    build: envs/golang
    image: dtc-golang
  python:
    build: envs/python
    image: dtc-python